apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux_developer
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/cgradwohl/flux_developer
  ref:
    branch: main
