apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-secrets-store
  namespace: kube-system
spec:
  chart:
    spec:
      chart: secrets-store-csi-driver
      sourceRef:
        kind: HelmRepository
        name: csi-driver
        namespace: flux-system
  interval: 10m
  install:
    createNamespace: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secrets-store-provider-aws
  namespace: kube-system
spec:
  chart:
    spec:
      chart: secrets-store-csi-driver-provider-aws
      sourceRef:
        kind: HelmRepository
        name: aws-secrets-manager
        namespace: flux-system
  interval: 10m
  install:
    createNamespace: false
