apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: csi-driver
  namespace: flux-system
spec:
  url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  interval: 10m
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aws-secrets-manager
  namespace: flux-system
spec:
  url: https://aws.github.io/secrets-store-csi-driver-provider-aws
  interval: 1h
