apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-secrets-store
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: "1.4.x"
      sourceRef:
        kind: HelmRepository
        name: csi-secrets-store
        namespace: flux-system
  values:
    syncSecret:
      enabled: true

    enableSecretRotation: true

    linux:
      enabled: true
